// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

// proto 包名，防止定义的消息类型命名冲突

package gin_micro

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	GetUsers(ctx context.Context, in *GetUsersReq, opts ...client.CallOption) (*GetUsersRsp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) GetUsers(ctx context.Context, in *GetUsersReq, opts ...client.CallOption) (*GetUsersRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.GetUsers", in)
	out := new(GetUsersRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	GetUsers(context.Context, *GetUsersReq, *GetUsersRsp) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		GetUsers(ctx context.Context, in *GetUsersReq, out *GetUsersRsp) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) GetUsers(ctx context.Context, in *GetUsersReq, out *GetUsersRsp) error {
	return h.UserServiceHandler.GetUsers(ctx, in, out)
}
